# Generated by Django 5.2.16 on 2026-07-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_banner',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'material categories',
                'db_table': 'content_material_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('chat_type', models.CharField(choices=[('open', 'Open'), ('invite', 'Invite'), ('service', 'Service')], default='open', max_length=20)),
                ('telegram_url', models.CharField(max_length=500)),
                ('min_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('access_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'content_telegram_chat',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('PROMPT', 'Prompt'), ('PDF', 'PDF'), ('DOC', 'DOC'), ('VIDEO', 'Video'), ('FLOW', 'Flow')], max_length=20)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('required_tariff', models.CharField(blank=True, max_length=20, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='content.materialcategory')),
            ],
            options={
                'db_table': 'content_material_group',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(max_length=20)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.materialgroup')),
            ],
            options={
                'db_table': 'content_material_file',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['group'], name='content_file_group_idx')],
            },
        ),
    ]
