# Generated by Django 5.2.16 on 2026-07-15 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activity_until', models.DateTimeField(blank=True, null=True)),
                ('tariff_lost_at', models.DateTimeField(blank=True, null=True)),
                ('current_rank', models.CharField(default='partner_1', max_length=50)),
                ('highest_rank', models.CharField(default='partner_1', max_length=50)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_partners', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_profile',
            },
        ),
        migrations.CreateModel(
            name='BinaryPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('depth', models.PositiveSmallIntegerField()),
                ('placed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='binary_children', to='partner.partnerprofile')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binary_placement', to='partner.partnerprofile')),
            ],
            options={
                'db_table': 'partner_binary_placement',
            },
        ),
        migrations.CreateModel(
            name='BinaryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_pv', models.PositiveIntegerField(default=0)),
                ('right_pv', models.PositiveIntegerField(default=0)),
                ('is_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binary_balance', to='partner.partnerprofile')),
            ],
            options={
                'db_table': 'partner_binary_balance',
            },
        ),
        migrations.CreateModel(
            name='SponsorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_link', to='partner.partnerprofile')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_invites', to='partner.partnerprofile')),
            ],
            options={
                'db_table': 'partner_sponsor_link',
            },
        ),
        migrations.AddIndex(
            model_name='partnerprofile',
            index=models.Index(fields=['invited_by'], name='partner_pro_invited_b19cad_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerprofile',
            index=models.Index(fields=['tariff_id'], name='partner_pro_tariff__9a4934_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerprofile',
            index=models.Index(fields=['is_active'], name='partner_pro_is_acti_8243eb_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerprofile',
            index=models.Index(fields=['current_rank'], name='partner_pro_current_380f72_idx'),
        ),
        migrations.AddIndex(
            model_name='binaryplacement',
            index=models.Index(fields=['parent', 'leg'], name='partner_bin_parent__074699_idx'),
        ),
        migrations.AddIndex(
            model_name='binaryplacement',
            index=models.Index(fields=['depth'], name='partner_bin_depth_70a860_idx'),
        ),
        migrations.AddConstraint(
            model_name='binaryplacement',
            constraint=models.UniqueConstraint(fields=('parent', 'leg'), name='partner_binary_unique_parent_leg'),
        ),
    ]
