# Generated by Django 5.2.16 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='binaryplacement',
            name='partner_binary_unique_parent_leg',
        ),
        migrations.AlterField(
            model_name='binaryplacement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='binary_children', to='partner.partnerprofile'),
        ),
        migrations.AddConstraint(
            model_name='binaryplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'leg'), name='partner_binary_unique_parent_leg'),
        ),
    ]
