# Generated by Django 5.2.16 on 2026-07-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_binary_parent_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('qualified_count', models.PositiveSmallIntegerField(default=0)),
                ('reward_paid', models.BooleanField(default=False)),
                ('reward_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fast_start', to='partner.partnerprofile')),
            ],
            options={
                'db_table': 'partner_fast_start',
            },
        ),
        migrations.CreateModel(
            name='QualificationWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('collapsed_pv', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_weeks', to='partner.partnerprofile')),
            ],
            options={
                'db_table': 'partner_qualification_week',
                'indexes': [models.Index(fields=['partner', 'week_start'], name='partner_qua_partner_21e069_idx')],
                'constraints': [models.UniqueConstraint(fields=('partner', 'week_start'), name='partner_qualification_week_unique')],
            },
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50)),
                ('premium_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('achieved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='partner.partnerprofile')),
            ],
            options={
                'db_table': 'partner_rank_history',
                'indexes': [models.Index(fields=['partner', 'achieved_at'], name='partner_ran_partner_7c6388_idx')],
            },
        ),
    ]
