from decimal import Decimal

ENTRY_TYPE_PURCHASE_PV = "purchase_pv"
ENTRY_TYPE_SUBSCRIPTION_PV = "subscription_pv"
ENTRY_TYPE_UPGRADE_PV = "upgrade_pv"
ENTRY_TYPE_BINARY_COLLAPSE = "binary_collapse"
ENTRY_TYPE_PERSONAL_BONUS = "personal_bonus"
ENTRY_TYPE_RENEWAL_BONUS = "renewal_bonus"
ENTRY_TYPE_BINARY_BONUS = "binary_bonus"
ENTRY_TYPE_MATCHING_BONUS = "matching_bonus"
ENTRY_TYPE_STATUS_PREMIUM = "status_premium"
ENTRY_TYPE_FAST_START_BONUS = "fast_start_bonus"
ENTRY_TYPE_ADJUSTMENT = "adjustment"
ENTRY_TYPE_WITHDRAWAL = "withdrawal"
ENTRY_TYPE_STORE_PURCHASE = "store_purchase"

ENTRY_TYPES = [
    ENTRY_TYPE_PURCHASE_PV,
    ENTRY_TYPE_SUBSCRIPTION_PV,
    ENTRY_TYPE_UPGRADE_PV,
    ENTRY_TYPE_BINARY_COLLAPSE,
    ENTRY_TYPE_PERSONAL_BONUS,
    ENTRY_TYPE_RENEWAL_BONUS,
    ENTRY_TYPE_BINARY_BONUS,
    ENTRY_TYPE_MATCHING_BONUS,
    ENTRY_TYPE_STATUS_PREMIUM,
    ENTRY_TYPE_FAST_START_BONUS,
    ENTRY_TYPE_ADJUSTMENT,
    ENTRY_TYPE_WITHDRAWAL,
    ENTRY_TYPE_STORE_PURCHASE,
]

BONUS_ENTRY_TYPES = [
    ENTRY_TYPE_BINARY_COLLAPSE,
    ENTRY_TYPE_PERSONAL_BONUS,
    ENTRY_TYPE_RENEWAL_BONUS,
    ENTRY_TYPE_BINARY_BONUS,
    ENTRY_TYPE_MATCHING_BONUS,
    ENTRY_TYPE_STATUS_PREMIUM,
    ENTRY_TYPE_FAST_START_BONUS,
]

DIRECTION_CREDIT = "credit"
DIRECTION_DEBIT = "debit"

DIRECTION_CHOICES = [
    (DIRECTION_CREDIT, "Зачисление"),
    (DIRECTION_DEBIT, "Списание"),
]

CURRENCY_USD = "USD"
CURRENCY_PV = "PV"

CURRENCY_CHOICES = [
    (CURRENCY_USD, "USD"),
    (CURRENCY_PV, "PV"),
]

DEFAULT_RULE_VERSION = "v1.0"

ENTRY_TYPE_TITLES = {
    ENTRY_TYPE_PURCHASE_PV: "PV за покупку",
    ENTRY_TYPE_SUBSCRIPTION_PV: "PV за подписку",
    ENTRY_TYPE_UPGRADE_PV: "PV за апгрейд",
    ENTRY_TYPE_BINARY_COLLAPSE: "Бинарный схлоп",
    ENTRY_TYPE_PERSONAL_BONUS: "Личный бонус",
    ENTRY_TYPE_RENEWAL_BONUS: "Бонус за продление",
    ENTRY_TYPE_BINARY_BONUS: "Бинарный бонус",
    ENTRY_TYPE_MATCHING_BONUS: "Матчинг-бонус",
    ENTRY_TYPE_STATUS_PREMIUM: "Статусная премия",
    ENTRY_TYPE_FAST_START_BONUS: "Fast Start",
    ENTRY_TYPE_ADJUSTMENT: "Корректировка",
    ENTRY_TYPE_WITHDRAWAL: "Вывод средств",
    ENTRY_TYPE_STORE_PURCHASE: "Покупка в маркете",
}

SOURCE_TYPE_ORDER = "order"
SOURCE_TYPE_PARTNER = "partner"
SOURCE_TYPE_ADMIN = "admin"
SOURCE_TYPE_WITHDRAWAL = "withdrawal"

DEFAULT_WITHDRAWAL_MIN_USD = Decimal("100")
DEFAULT_WITHDRAWAL_MAX_PER_REQUEST_USD = Decimal("10000")
DEFAULT_WITHDRAWAL_CURRENCY = "USDT"

DEBT_STATUS_OPEN = "open"
DEBT_STATUS_PAID = "paid"
DEBT_STATUS_CANCELLED = "cancelled"

DEBT_STATUS_CHOICES = [
    (DEBT_STATUS_OPEN, "Открыт"),
    (DEBT_STATUS_PAID, "Оплачен"),
    (DEBT_STATUS_CANCELLED, "Отменён"),
]
