# Generated by Django 5.2.16 on 2026-07-17 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('commerce', '0002_lesson_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['sort_order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.AlterModelOptions(
            name='lessonresource',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Материал урока', 'verbose_name_plural': 'Материалы уроков'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['sort_order'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='moduleprogress',
            options={'verbose_name': 'Прогресс по модулю', 'verbose_name_plural': 'Прогресс по модулям'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Прогресс по программе', 'verbose_name_plural': 'Прогресс по программам'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите mp4/webm сюда — файл попадёт в backend/media/lessons/. Удобно для локального демо.', null=True, upload_to='lessons/', verbose_name='Файл видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='О чём урок (можно коротко).', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Примерная длина в минутах, например 12.', null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ibox_scenario_id',
            field=models.BigIntegerField(blank=True, help_text='ID сценария AI Hub, если урок связан с чатом. Обычно пусто.', null=True, verbose_name='Сценарий AI Hub'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Видео'), ('practice', 'Практика'), ('reading', 'Чтение')], default='video', max_length=20, verbose_name='Тип урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='result_description',
            field=models.TextField(blank=True, help_text='Что ученик получит после прохождения — показывается в карточке урока.', null=True, verbose_name='Результат урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='sort_order',
            field=models.SmallIntegerField(help_text='Порядок урока в модуле: 1, 2, 3…', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_quality',
            field=models.CharField(blank=True, help_text='Подпись качества, например HD. Можно оставить пустым.', max_length=10, null=True, verbose_name='Качество видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.TextField(blank=True, help_text='Внешняя ссылка (CDN/YouTube-direct mp4) или путь /media/lessons/…. Если загружен файл ниже — файл имеет приоритет.', null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='academy.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начато'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='video_position_sec',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция в видео (сек)'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='content',
            field=models.TextField(blank=True, help_text='Текст задания или конспекта, если нет файла.', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file_url',
            field=models.TextField(blank=True, help_text='URL файла или путь /media/…', null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academy.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='resource_type',
            field=models.CharField(choices=[('summary', 'Конспект'), ('template', 'Шаблон'), ('practice', 'Практика'), ('file', 'Файл')], max_length=30, verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='sort_order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_intro',
            field=models.BooleanField(default=False, help_text='Отметьте, если это короткое введение в начале курса.', verbose_name='Вводный модуль'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='module',
            name='lesson_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число уроков'),
        ),
        migrations.AlterField(
            model_name='module',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academy.program', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sort_order',
            field=models.SmallIntegerField(help_text='Порядок модуля внутри программы: 0, 1, 2…', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='completed_lessons',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено уроков'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='academy.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_module_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Короткий текст под названием на карточке и в карточке курса.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.CharField(blank=True, help_text='Пока можно оставить пустым — в кабинете подставится стандартная иконка.', max_length=50, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Включите, когда программа готова. Неопубликованная в кабинете не видна.', verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='program',
            name='lesson_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число уроков'),
        ),
        migrations.AlterField(
            model_name='program',
            name='module_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число модулей'),
        ),
        migrations.AlterField(
            model_name='program',
            name='required_product',
            field=models.ForeignKey(blank=True, help_text='Опционально: если доступ даётся только после покупки конкретного продукта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_programs', to='commerce.product', verbose_name='Нужный продукт'),
        ),
        migrations.AlterField(
            model_name='program',
            name='required_tariff',
            field=models.CharField(blank=True, help_text='Код тарифа для доступа: rise, rise-pro или rise-pro-max. Пусто — без ограничения по тарифу.', max_length=20, null=True, verbose_name='Минимальный тариф'),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.CharField(help_text='Латиницей без пробелов, например gpt-new. Используется в адресе /courses/gpt-new. Обычно заполняется сам из названия.', max_length=100, unique=True, verbose_name='Код в ссылке (slug)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='sort_order',
            field=models.SmallIntegerField(default=0, help_text='Чем меньше число, тем выше в списке (0, 1, 2…).', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Список меток в формате JSON. Пример: ["HIT"] или ["Новинка", "Хит"]. На главной показывается первый тег как бейдж.', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(help_text='Как программа называется в кабинете, например «GPT - NEW».', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_lessons',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено уроков'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_modules',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено модулей'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.lesson', verbose_name='Последний урок'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='academy.program', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс %'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начато'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_program_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
