# Generated by Django 5.2.16 on 2026-07-15 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('rules', models.JSONField()),
                ('effective_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_rule_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_rule_version',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_adjustment_debts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_adjustment_debt',
                'indexes': [models.Index(fields=['user', 'status'], name='ledger_adju_user_id_05bc2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('purchase_pv', 'purchase_pv'), ('subscription_pv', 'subscription_pv'), ('upgrade_pv', 'upgrade_pv'), ('binary_collapse', 'binary_collapse'), ('personal_bonus', 'personal_bonus'), ('renewal_bonus', 'renewal_bonus'), ('binary_bonus', 'binary_bonus'), ('matching_bonus', 'matching_bonus'), ('status_premium', 'status_premium'), ('fast_start_bonus', 'fast_start_bonus'), ('adjustment', 'adjustment'), ('withdrawal', 'withdrawal')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PV', 'PV')], default='USD', max_length=5)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ruleversion')),
            ],
            options={
                'db_table': 'ledger_entry',
                'indexes': [models.Index(fields=['user', '-created_at'], name='ledger_entr_user_id_6a55e0_idx'), models.Index(fields=['entry_type', '-created_at'], name='ledger_entr_entry_t_990c3e_idx'), models.Index(fields=['source_type', 'source_id'], name='ledger_entr_source__16ac58_idx'), models.Index(fields=['currency', 'user'], name='ledger_entr_currenc_6009e3_idx')],
            },
        ),
    ]
