# Generated by Django 5.2.16 on 2026-07-15 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_balance',
            },
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('network', models.CharField(choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_saved_address',
                'indexes': [models.Index(fields=['user', 'is_default'], name='wallet_save_user_id_9cd337_idx')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usdt_address', models.CharField(max_length=128)),
                ('network', models.CharField(choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_withdrawal_request',
                'indexes': [models.Index(fields=['user', 'status'], name='wallet_with_user_id_116054_idx'), models.Index(fields=['status', 'created_at'], name='wallet_with_status_6c04c2_idx')],
            },
        ),
    ]
