# Generated by Django 5.2.16 on 2026-07-15 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedaddress',
            constraint=models.UniqueConstraint(fields=('user', 'network'), name='wallet_saved_address_user_network'),
        ),
    ]
