# Generated by Django 5.2.16 on 2026-07-17 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='tariffplan',
            options={'verbose_name': 'Тарифный план', 'verbose_name_plural': 'Тарифные планы'},
        ),
        migrations.AlterModelOptions(
            name='useraccess',
            options={'verbose_name': 'Доступ пользователя', 'verbose_name_plural': 'Доступы пользователей'},
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, USD'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('purchase', 'Покупка'), ('upgrade', 'Апгрейд'), ('renewal', 'Продление')], max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='previous_tariff_id',
            field=models.CharField(blank=True, help_text='При апгрейде — ID старого тарифа', max_length=20, null=True, verbose_name='Предыдущий тариф'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('expired', 'Истёк'), ('cancelled', 'Отменён'), ('refunded', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, USD'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency_crypto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Криптовалюта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Инструкции'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='commerce.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('expired', 'Истёк'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='webhook_payload',
            field=models.JSONField(blank=True, help_text='{"event": "..."}', null=True, verbose_name='Данные webhook'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='{"key": "value"}', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена, USD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('tariff', 'Тариф'), ('subscription', 'Подписка'), ('tokens', 'Токены'), ('program', 'Программа')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active_until',
            field=models.DateTimeField(verbose_name='Активна до'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Автопродление'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_renewal_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее продление'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tariff_id',
            field=models.CharField(max_length=20, verbose_name='ID тарифа'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='binary_depth',
            field=models.PositiveSmallIntegerField(verbose_name='Глубина бинара'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='included_months',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Месяцев в тарифе'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='initial_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Начальные токены'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='matching_lines',
            field=models.PositiveSmallIntegerField(verbose_name='Линий матчинга'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='personal_bonus_cap_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Лимит личного бонуса, USD'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_plan', to='commerce.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='purchase_pv_cap',
            field=models.PositiveIntegerField(verbose_name='Лимит PV за покупку'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='quick_start_eligible',
            field=models.BooleanField(default=False, verbose_name='Участвует в Fast Start'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='tariff_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID тарифа'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='granted_at',
            field=models.DateTimeField(verbose_name='Выдан'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='commerce.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to='commerce.order', verbose_name='Заказ-источник'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
